### ISSUE TITLE
Cannot find module 'bourbon'

### ISSUE THREAD

**Issue by tian-Sun** [javallone/regexper-static#35]
do → npm start

above is npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart regexper@1.0.0
6 info start regexper@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info regexper@1.0.0 Failed to exec start script
9 verbose stack Error: regexper@1.0.0 start: `gulp server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid regexper@1.0.0
11 verbose cwd /Users/tianhuiting/front_end/regexper-static
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error regexper@1.0.0 start: `gulp server`
17 error Exit status 1
18 error Failed at the regexper@1.0.0 start script 'gulp server'.
18 error This is most likely a problem with the regexper package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs regexper
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls regexper
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by tian-Sun** [comment]
and i had do → npm install

**Comment by tian-Sun** [comment]
o, bourbon = require('node-bourbon');
